name: CI/CD SaraBank

on:
  workflow_dispatch:
    inputs:
      gcp_sa_key:
        description: 'Conteúdo completo da Chave JSON da Service Account do GCP'
        required: true
        type: string
      firebase_api_key:
        description: 'Firebase API Key'
        required: true
        type: string
      project_id:
        description: 'ID do projeto no GCP'
        required: true
        type: string

env:
  REGION: 'us-central1'
  SERVICE: 'sarabank-api'
  REPO: 'sarabank-repo'

jobs:
  # ---------------------------------------------------------
  # JOB 1: Compilação (Build)
  # ---------------------------------------------------------
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restaurar Dependências
      run: dotnet restore src/

    - name: Build da Solução
      run: dotnet build src/ --no-restore -c Release

  # ---------------------------------------------------------
  # JOB 2: Testes Unitários
  # ---------------------------------------------------------
  test:
    needs: build # Só testa se o build passar
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restaurar Dependências
      run: dotnet restore src/

    - name: Executar Testes
      run: dotnet test src/ --no-restore --verbosity normal

  # ---------------------------------------------------------
  # JOB 3: Deploy (CD)
  # ---------------------------------------------------------
  deploy:
    needs: test # se os testes passarem avança
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
    - name: Checkout Código
      uses: actions/checkout@v4

    - name: Autenticar no Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ github.event.inputs.gcp_sa_key }}'

    - name: Configurar Docker para Artifact Registry
      run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

    - name: Build e Push da Imagem Docker
      run: |
        DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ github.event.inputs.project_id }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ github.sha }}"
        docker build -t $DOCKER_TAG -f src/SaraBank.API/Dockerfile .
        docker push $DOCKER_TAG

    - name: Deploy no Cloud Run
      id: deploy_step
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        service: ${{ env.SERVICE }}
        region: ${{ env.REGION }}
        image: ${{ env.REGION }}-docker.pkg.dev/${{ github.event.inputs.project_id }}/${{ env.REPO }}/${{ env.SERVICE }}:${{ github.sha }}
        env_vars: |
          Firebase__ApiKey=${{ github.event.inputs.firebase_api_key }}
          ASPNETCORE_ENVIRONMENT=Development
          ASPNETCORE_URLS=http://0.0.0.0:8080
        flags: '--allow-unauthenticated'

    - name: Exibir Link do Swagger
      run: |
        echo "===================================================="
        echo "SUCESSO! ACESSE O SWAGGER EM:"
        echo "${{ steps.deploy_step.outputs.url }}/swagger"
        echo "===================================================="